#!/bin/sh

pushd .

# paths
KBPATH='/vagrant/killbill-source' # base path for source compiling
DEPLOYPATH='/var/tmp/tomcat/webapps'
DEPLOYNAME='ROOT'

# KB version name to deploy
KBVER='0.12.1'

# git tags to check out
KBTAG="killbill-$KBVER"
OSSPARENTTAG="killbill-oss-parent-0.9.2"
COMMONSTAG="killbill-commons-0.2.28"
PLATFORMTAG="killbill-platform-0.1.1"

mkdir -p $KBPATH
 
echo "cloning repositories"
cd $KBPATH
git clone http://github.com/killbill/killbill # killbill-0.12.1
git clone http://github.com/killbill/killbill-oss-parent # killbill-oss-parent-0.9.2
git clone http://github.com/killbill/killbill-commons #killbill-commons-0.2.28
git clone http://github.com/killbill/killbill-platform #killbill-platform-0.1.1
 
echo "checking out release versions"
cd $KBPATH/killbill && git checkout $KBTAG
cd $KBPATH/killbill-oss-parent && git checkout $OSSPARENTTAG
cd $KBPATH/killbill-commons && git checkout $COMMONSTAG
cd $KBPATH/killbill-platform && git checkout $PLATFORMTAG

echo "building source"
cd $KBPATH/killbill-oss-parent && mvn clean install
cd $KBPATH/killbill-commons && mvn clean install
cd $KBPATH/killbill-platform && mvn clean install
cd $KBPATH/killbill && mvn clean install
 
echo "packaging source"
cd $KBPATH/killbill && mvn package

echo "deploying package"
sudo rm -rf $DEPLOYPATH/$DEPLOYNAME
sudo rm $DEPLOYPATH/$DEPLOYNAME.war
sudo cp $KBPATH/killbill/profiles/killbill/target/killbill-profiles-killbill-$KBVER.war $DEPLOYPATH/$DEPLOYNAME.war

echo "killbill $KBVER deployed from sources: "
echo "killbill: $KBTAG"
echo "killbill-platform: $PLATFORMTAG"
echo "killbill-commons: $COMMONSTAG"
echo "killbill-oss-parent: $OSSPARENTTAG"

popd